/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import AdministrationPanels.EspaceFacturation;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sidi Mohamed
 */
public class PanneauImpressionSecondaire extends javax.swing.JPanel {
    public DefaultTableModel tableModel ;
    /**
     * Creates new form PanneauImpressionSecondaire
     */
    public PanneauImpressionSecondaire() {
        initComponents();
        this.initTable();
    }
    public boolean isFull(){
        if(this.tableModel.getRowCount() == EspaceFacturation.k2)return true;
        else return false;
    }
    private void initTable(){
        tableModel = new DefaultTableModel();
        Object[] objets = {"N°","Type cafe","Quantite (Kg)","P.U (DA)","Prix Total HT (DA)","Avance (DA)","Reste (DA)"};
        tableModel.setColumnIdentifiers(objets);
        this.jTable1 = new JTable();
        jTable1.setModel(tableModel);
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setRowHeight(23);
        jTable1.setColumnSelectionAllowed(false);
        jTable1.setGridColor(Color.black);
        jTable1.setShowVerticalLines(true);
        jTable1.setShowHorizontalLines(true);
        jTable1.setFillsViewportHeight(true);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(120);
        jTable1.setBackground(Color.white);
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.removeColumn((jTable1.getColumnModel().getColumn(5)));
        jTable1.removeColumn((jTable1.getColumnModel().getColumn(5)));
        jScrollPane1.setBackground(Color.white);
        jScrollPane1.setViewportView(jTable1);
    }
    public void setNewRow(int compteur,String typeAchat,double quantite,double PU,double prixTotal,double avance,double reste){
        Object[] donnees = {compteur,typeAchat,quantite,PU,prixTotal,avance,reste};
        tableModel.addRow(donnees);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(0, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setPreferredSize(new java.awt.Dimension(621, 718));
        jTable1.setRowHeight(23);
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
