/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ModeledWindows;

import MainPackage.IOTransactions;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author Sidi Mohamed
 */
public class IDPWChanger extends javax.swing.JFrame {
    int indice = -1;
    /**
     * Creates new form IDPWChanger
     */
    public IDPWChanger() {
        initComponents();
        this.jButton1.addActionListener(new ActionListener(){
           public void actionPerformed(ActionEvent e){
               updateInformation();
           } 
        });
        this.jButton2.addActionListener(new ActionListener(){
           public void actionPerformed(ActionEvent e){
               setVisible(false);
               jTextField1.setText("");
               jTextField2.setText("");
           } 
        });
        this.setSize(440, 160);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        IntroductionWindow.barre.setValue(IntroductionWindow.barre.getValue()+1);
    }
    public void setLabelsInformations(int indice){
        this.indice = indice;
        switch(this.indice){
            case 0:
                this.setTitle("Mise à jour du nom d'utilisateur");
                jLabel1.setText("Nom d'utilisateur antérieur:");
                jLabel2.setText("Nouveau nom d'utilisateur");
                break;
            case 1:
                this.setTitle("Mise à jour du mot de passe");
                jLabel1.setText("Mot de passe antérieur");
                jLabel2.setText("Nouveau mot de passe");
                break;
        }
    }
    private void updateInformation(){
        try{
            Statement state = IOTransactions.getConnectionUtility().createStatement(
                    ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            ResultSet result = state.executeQuery("select * from CONSTANTES");
            result.absolute(indice + 9);
            if(jTextField1.getText().equals(result.getString("VALEUR_CONST_S"))){
                if(jTextField2.getText().length() >= 6){
                    result.updateString("VALEUR_CONST_S", jTextField2.getText());
                    result.updateRow();
                    setVisible(false);
                    jTextField1.setText("");
                    jTextField2.setText("");
                }
                else {
                    JOptionPane p = new JOptionPane();
                    p.showMessageDialog(null,"L'information entrée doit avoir au moins 6 caractères",
                            "Erreur...",JOptionPane.ERROR_MESSAGE);
                }
            }
            else {
                JOptionPane p = new JOptionPane();
                p.showMessageDialog(null,"L'information entrée est incorrecte",
                            "Erreur...",JOptionPane.ERROR_MESSAGE);
            }
            result.close();
            state.close();
        }
        catch(NullPointerException | ClassNotFoundException | SQLException e){e.printStackTrace();}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setMaximumSize(new java.awt.Dimension(440, 130));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Nom d'utilisateur antérieur:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, 25));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nouveau nom d'utilisateur:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 44, 207, 25));

        jButton1.setText("Confirmer");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 89, 207, 35));

        jButton2.setText("Annuler");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 89, 207, 35));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 13, 207, 25));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 46, 207, 25));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDPWChanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDPWChanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDPWChanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDPWChanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IDPWChanger().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
